name: Zephyr development container

on:
  schedule:
    - cron: '24 8 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        arch: [x86_64]
        sdk: [0.16.4]
        zephyr: [main,v3.4.0]
        tool: [
          { prefix: "aarch64", suffix: "-zephyr-elf"},
          { prefix: "arc64", suffix: "-zephyr-elf"},
          { prefix: "arc", suffix: "-zephyr-elf"},
          { prefix: "arm", suffix: "-zephyr-eabi"},
          { prefix: "microblazeel", suffix: "-zephyr-elf"},
          { prefix: "mips", suffix: "-zephyr-elf"},
          { prefix: "nios2", suffix: "-zephyr-elf"},
          { prefix: "riscv64", suffix: "-zephyr-elf"},
          { prefix: "sparc", suffix: "-zephyr-elf"},
          { prefix: "x86_64", suffix: "-zephyr-elf"},
          { prefix: "xtensa-espressif_esp32", suffix: "_zephyr-elf"},
          { prefix: "xtensa-espressif_esp32s2", suffix: "_zephyr-elf"},
          { prefix: "xtensa-espressif_esp32s3", suffix: "_zephyr-elf"},
          { prefix: "xtensa-intel_ace15_mtpm", suffix: "_zephyr-elf"},
          { prefix: "xtensa-intel_tgl_adsp", suffix: "_zephyr-elf"},
          { prefix: "xtensa-nxp_imx_adsp", suffix: "_zephyr-elf"},
          { prefix: "xtensa-nxp_imx8m_adsp", suffix: "_zephyr-elf"},
          { prefix: "xtensa-nxp_imx8ulp_adsp", suffix: "_zephyr-elf"},
          { prefix: "xtensa-sample_controller", suffix: "_zephyr-elf"},
          { prefix: "xtensa-mt8195_adsp", suffix: "_zephyr-elf"},
          { prefix: "nxp_adsp_rt500", suffix: "" },
          { prefix: "qemu_xtensa_dc233c", suffix: ""}
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.actor }}/zephyr-${{ matrix.tool.prefix }}:${{ matrix.zephyr }}-${{ matrix.sdk }}sdk
          build-args: |
            ARCHITECTURE=${{ matrix.arch }}
            ZEPHYR_SDK_VERSION=${{ matrix.sdk }}
            ZEPHYR_VERSION=${{ matrix.zephyr }}
            TOOLCHAIN=${{ matrix.tool.prefix }}${{ matrix.tool.suffix }}
